### ISSUE TITLE
Release in formula does not exist

### ISSUE THREAD

**Issue by MattLewin** [Ether-CLI/homebrew-tap#2]
Release 2018.09.02, as specified in `ether.rb` resulting from change 459184d does not exist. The most recent obtainable release is 2018.08.11, as seen [here](https://github.com/Ether-CLI/Ether/releases).

This results in attached very unpleasant output from `brew install`

<img width="652" alt="brew ether install fail" src="https://user-images.githubusercontent.com/7084481/45173308-cb31f780-b1d5-11e8-9fe9-cfa563466d51.png">

**Comment by calebkleveter** [comment]
Yeah, sorry 😬. Installs are uncommon enough I was hoping I could get away with removing the GitHub release and being lazy. I will get this fixed ASAP.

**Comment by calebkleveter** [comment]
Alright, should be fixed now!
